-- ID  	EMAIL  	FIRST_NAME  	LAST_NAME  	PHONE_NUMBER  	PHONE_TYPE  

--INSERT INTO CONTACT(EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,PHONE_TYPE)
 --VALUES('amex2000@gmail.com','Amanuel','Gebru','641-233-0149','MOBILE');
 
 --INSERT INTO CONTACT(EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,PHONE_TYPE)
 --VALUES('belay@gmail.com','Belay','Hagos','641-453-9870','MOBILE');
 
 --INSERT INTO CONTACT(EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,PHONE_TYPE)
 --VALUES('selam@gmail.com','Selam','Berhe','641-655-0189','OFFICE');
 

 --INSERT INTO CONTACT_NOTE(MESSAGE) VALUES("How you doing");


-- 
-- Inserting into CONTACT_NOTE
--INSERT INTO CONTACT_NOTE(MESSAGE,CONTACT_ID) VALUES("How you doing");
--INSERT INTO CONTACT_NOTE(MESSAGE) VALUES("How yu doing man");
--INSERT INTO CONTACT_NOTE(MESSAGE) VALUES("Hey");
--INSERT INTO CONTACT_NOTE(MESSAGE VALUES("Hello Body");


